#config/packages/security.yaml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    superadmin:
                        password: 'superadminpw'
                        roles: ['ROLE_SUPER_ADMIN']
        fos_userbundle:
            id: fos_user.user_provider.username
    
    firewalls:
        
        api_login:
            pattern:  ^/api/user/login
            stateless: true
            anonymous: true
            json_login:
                provider: chain_provider
                check_path: /api/user/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            provider: chain_provider
        api:
            pattern:   ^/api              # protected path
            stateless: true
            provider: 'chain_provider'
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator    
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false        
        main:
            pattern: ^/
            anonymous:    true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/check-for-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/allSubjects, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/allActiveSubjects, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/addSubject, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/allCourses/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/allActiveCourses/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/addCourse, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/addTopic, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/allTopics, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/allActiveTopics, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, role: ROLE_ADMIN }        