#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_auth_login:
    path: /api/user/login
    methods:  [POST]
api_heart:
    prefix: /api
    resource: '../src/Controller/Api'
fos_user: 
     resource: "@FOSUserBundle/Resources/config/routing/all.xml"         